# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.14.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "psc-package.json" }}

      - run: npm i purescript@0.12.0
      - run: sudo cp node_modules/.bin/purs /usr/local/bin/purs

      - run: npm i psc-package@3.0.0
      - run: sudo cp node_modules/.bin/psc-package /usr/local/bin/psc-package

      - run: npm i pulp@12.3.0

      - run: node_modules/.bin/psc-package install

      - run: node_modules/.bin/pulp browserify -t app.js -O

      - save_cache:
          paths:
            - .psc-package
            - output
          key: v3-dependencies-{{ checksum "psc-package.json" }}

      - run: git config --global user.email "circle@ci.com"
      - run: git config --global user.name "CircleCI"
      - run: git checkout -b gh-pages
      - run: git add app.js
      - run: git commit -m "CI commit app.js"
      - run: git push -f origin gh-pages
